//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Agenda.au.edu.wa.central.mydesign.student {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateItemDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMeetingTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadMeetingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadMeetingDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadItemDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://student.mydesign.central.wa.edu.au/2016CertIV_8/Service1.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event UpdateItemDetailsCompletedEventHandler UpdateItemDetailsCompleted;
        
        /// <remarks/>
        public event UpdateMeetingTimeCompletedEventHandler UpdateMeetingTimeCompleted;
        
        /// <remarks/>
        public event LoadMeetingsCompletedEventHandler LoadMeetingsCompleted;
        
        /// <remarks/>
        public event LoadMeetingDetailsCompletedEventHandler LoadMeetingDetailsCompleted;
        
        /// <remarks/>
        public event LoadItemsCompletedEventHandler LoadItemsCompleted;
        
        /// <remarks/>
        public event LoadItemDetailsCompletedEventHandler LoadItemDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Login([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password) {
            object[] results = this.Invoke("Login", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string password) {
            this.LoginAsync(username, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        username,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UpdateItemDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateItemDetails([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string notes, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string time, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string itemName) {
            this.Invoke("UpdateItemDetails", new object[] {
                        notes,
                        time,
                        itemName});
        }
        
        /// <remarks/>
        public void UpdateItemDetailsAsync(string notes, string time, string itemName) {
            this.UpdateItemDetailsAsync(notes, time, itemName, null);
        }
        
        /// <remarks/>
        public void UpdateItemDetailsAsync(string notes, string time, string itemName, object userState) {
            if ((this.UpdateItemDetailsOperationCompleted == null)) {
                this.UpdateItemDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateItemDetailsOperationCompleted);
            }
            this.InvokeAsync("UpdateItemDetails", new object[] {
                        notes,
                        time,
                        itemName}, this.UpdateItemDetailsOperationCompleted, userState);
        }
        
        private void OnUpdateItemDetailsOperationCompleted(object arg) {
            if ((this.UpdateItemDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateItemDetailsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UpdateMeetingTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMeetingTime([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string time, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string meetingName) {
            this.Invoke("UpdateMeetingTime", new object[] {
                        time,
                        meetingName});
        }
        
        /// <remarks/>
        public void UpdateMeetingTimeAsync(string time, string meetingName) {
            this.UpdateMeetingTimeAsync(time, meetingName, null);
        }
        
        /// <remarks/>
        public void UpdateMeetingTimeAsync(string time, string meetingName, object userState) {
            if ((this.UpdateMeetingTimeOperationCompleted == null)) {
                this.UpdateMeetingTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMeetingTimeOperationCompleted);
            }
            this.InvokeAsync("UpdateMeetingTime", new object[] {
                        time,
                        meetingName}, this.UpdateMeetingTimeOperationCompleted, userState);
        }
        
        private void OnUpdateMeetingTimeOperationCompleted(object arg) {
            if ((this.UpdateMeetingTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMeetingTimeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/LoadMeetings", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] LoadMeetings() {
            object[] results = this.Invoke("LoadMeetings", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void LoadMeetingsAsync() {
            this.LoadMeetingsAsync(null);
        }
        
        /// <remarks/>
        public void LoadMeetingsAsync(object userState) {
            if ((this.LoadMeetingsOperationCompleted == null)) {
                this.LoadMeetingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadMeetingsOperationCompleted);
            }
            this.InvokeAsync("LoadMeetings", new object[0], this.LoadMeetingsOperationCompleted, userState);
        }
        
        private void OnLoadMeetingsOperationCompleted(object arg) {
            if ((this.LoadMeetingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadMeetingsCompleted(this, new LoadMeetingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/LoadMeetingDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] LoadMeetingDetails([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string selected) {
            object[] results = this.Invoke("LoadMeetingDetails", new object[] {
                        selected});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void LoadMeetingDetailsAsync(string selected) {
            this.LoadMeetingDetailsAsync(selected, null);
        }
        
        /// <remarks/>
        public void LoadMeetingDetailsAsync(string selected, object userState) {
            if ((this.LoadMeetingDetailsOperationCompleted == null)) {
                this.LoadMeetingDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadMeetingDetailsOperationCompleted);
            }
            this.InvokeAsync("LoadMeetingDetails", new object[] {
                        selected}, this.LoadMeetingDetailsOperationCompleted, userState);
        }
        
        private void OnLoadMeetingDetailsOperationCompleted(object arg) {
            if ((this.LoadMeetingDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadMeetingDetailsCompleted(this, new LoadMeetingDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/LoadItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] LoadItems([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string selected) {
            object[] results = this.Invoke("LoadItems", new object[] {
                        selected});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void LoadItemsAsync(string selected) {
            this.LoadItemsAsync(selected, null);
        }
        
        /// <remarks/>
        public void LoadItemsAsync(string selected, object userState) {
            if ((this.LoadItemsOperationCompleted == null)) {
                this.LoadItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadItemsOperationCompleted);
            }
            this.InvokeAsync("LoadItems", new object[] {
                        selected}, this.LoadItemsOperationCompleted, userState);
        }
        
        private void OnLoadItemsOperationCompleted(object arg) {
            if ((this.LoadItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadItemsCompleted(this, new LoadItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/LoadItemDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] LoadItemDetails([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string selected) {
            object[] results = this.Invoke("LoadItemDetails", new object[] {
                        selected});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void LoadItemDetailsAsync(string selected) {
            this.LoadItemDetailsAsync(selected, null);
        }
        
        /// <remarks/>
        public void LoadItemDetailsAsync(string selected, object userState) {
            if ((this.LoadItemDetailsOperationCompleted == null)) {
                this.LoadItemDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadItemDetailsOperationCompleted);
            }
            this.InvokeAsync("LoadItemDetails", new object[] {
                        selected}, this.LoadItemDetailsOperationCompleted, userState);
        }
        
        private void OnLoadItemDetailsOperationCompleted(object arg) {
            if ((this.LoadItemDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadItemDetailsCompleted(this, new LoadItemDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateItemDetailsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateMeetingTimeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LoadMeetingsCompletedEventHandler(object sender, LoadMeetingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadMeetingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadMeetingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LoadMeetingDetailsCompletedEventHandler(object sender, LoadMeetingDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadMeetingDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadMeetingDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LoadItemsCompletedEventHandler(object sender, LoadItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LoadItemDetailsCompletedEventHandler(object sender, LoadItemDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadItemDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadItemDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591